baseurl         = "http://carlosleon.info"
title           = "Carlos León"
theme           = "herring-cove"
googleanalytics = "UA-77086456-2"

[params]
  profilepicture         = "/img/profile.jpg"
  description            = "Cloud Expert"
  author                 = "Carlos León"
  authorname             = "Carlos León"
  twitter                = "https://twitter.com/mongrelion"
  github                 = "https://github.com/mongrelion"
  linkedin               = "https://linkedin.com/in/mongrelion"
  enablelandingpage      = true
  landingpageredirecturl = "/about"

[params.links]
  about = "/about"
