version: "2"

services:
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    ports:
      - "8080:80"

  blog:
    build: .
    ports:
      - "9292:9292"
